[package]
name = "iceoryx2-tunnel-backend"
description = "iceoryx2: traits and types for implementing tunnel backends"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
iceoryx2 = { workspace = true }
iceoryx2-bb-posix = { workspace = true }
