[package]
name = "iceoryx2-tunnels-traits"
description = "iceoryx2: traits describing tunnel functionality"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]
name = "iceoryx2_tunnels_traits"
path = "src/lib.rs"

[dependencies]
iceoryx2 = { workspace = true }

